name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GO_VERSION: 1.18

jobs:
  build:
    strategy:
      matrix:
        go_arch: [amd64, arm64]
        go_os: [linux, darwin]
        mode: [release, dev]
        tag: ['', 'libvirt']
    env:
      OUTPUT: bin/openshift-install-${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
    runs-on: ${{ matrix.go_os == 'darwin' && 'macos-latest' || 'ubuntu-latest' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          export MODE=$mode
          export GIT_TAG=${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          export OUTPUT=${{ env.OUTPUT }}

          # build the binary
          if [[ "${go_os}" == "darwin" ]]; then
            env GOOS=darwin GOARCH=${go_arch} make clean all
          else
            ./hack/build.sh
          fi

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          name: master-${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          tag: master-${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          body: Release ${{ matrix.tag }} for ${{ matrix.mode }} mode on ${{ matrix.go_os }}-${{ matrix.go_arch }}
          prerelease: false
          artifacts: ${{ env.OUTPUT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
