name: build

on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.18

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_arch: [amd64, arm64]
        go_os: [linux, darwin]
        mode: [release, dev]
        tag: ['', 'libvirt']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Terraform
        run: |
          cd hack/terraform
          make all
          cd -

      - name: Copy Terraform to mirror
        run: |
          cd hack
          sh copy_terraform_to_mirror.sh
          cd -

      - name: Build
        run: |
          export CGO_ENABLED=0
          export DEFAULT_ARCH=$go_arch
          export GOOS=$go_os
          export GOARCH=$go_arch
          export MODE=$mode
          export TAGS=$tag
          export OUTPUT=bin/openshift-install-$MODE-$go_os-$go_arch
          export GIT_COMMIT=${{ env.SOURCE_GIT_COMMIT:-$(git rev-parse --verify 'HEAD^{commit}')}}

          # build the binary
          go build -o $OUTPUT ./cmd/openshift-install

      - name: Create Release
        uses: ncipollo/release-action@v2.5.0
        with:
          name: ${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          tag: ${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          body: Release ${{ matrix.tag }} for ${{ matrix.mode }} mode on ${{ matrix.go_os }}-${{ matrix.go_arch }}
          prerelease: false
          files: ${{ env.OUTPUT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
