name: build

on:
  push:
    branches:
      - master

env:
  GO_VERSION: 1.18

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_arch: [amd64, arm64]
        go_os: [linux, darwin]
        mode: [release, dev]
        tag: ['', 'libvirt']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: |
          export MODE=$mode
          export GIT_TAG=${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          export OUTPUT=bin/openshift-install-${GIT_TAG}

          # build the binary
          ./hack/build.sh

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          tag: ${{ matrix.tag }}-${{ matrix.mode }}-${{ matrix.go_os }}-${{ matrix.go_arch }}
          body: Release ${{ matrix.tag }} for ${{ matrix.mode }} mode on ${{ matrix.go_os }}-${{ matrix.go_arch }}
          prerelease: false
          files: ${{ env.OUTPUT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
